### ISSUE TITLE
alternative download links

### ISSUE THREAD

**Issue by yikuan8** [MedicineBiology-AI/EEG-DTI#1]
Thanks for the great repo. Do you have a plan of providing an alternative approach to download the dataset (drive, box, and etc.)?

**Comment by ddomingof** [comment]
![Uploading Screenshot 2021-02-01 at 20.56.34.png…]()
I get the following error...

**Comment by GeniusYx** [comment]
@YIKUAN8 The data can be found in this link https://github.com/MedicineBiology-AI/EEG-DTI/tree/master

**Comment by ddomingof** [comment]
https://pan.baidu.com/s/1vLRG1M9vgRJn5PpCDVizkg this link is not working...

**Comment by GeniusYx** [comment]
@ddomingof Sorry, I can not see the picture.
<img width="465" alt="image" src="https://user-images.githubusercontent.com/18549296/106572132-038abb00-6573-11eb-9c94-2f19782596c4.png">

**Comment by GeniusYx** [comment]
@ddomingof  Thank you for your interest. The data can be found in this link https://github.com/MedicineBiology-AI/EEG-DTI/tree/master
