### ISSUE TITLE
In python 3.7.8 and tensorflow=1.15.0 , running main_yamanashi.py has the following error.

### ISSUE THREAD

**Issue by Daiqh1** [MedicineBiology-AI/EEG-DTI#3]
![图片](https://user-images.githubusercontent.com/76582524/147546878-7e22ad37-38bd-423e-8585-990c578f0a12.png)

**Comment by GeniusYx** [comment]
Maybe you need to change the following settings according to the number of layers of GCN：

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/18549296/147548922-62b2875d-1641-43cb-9c0e-48250ee76c4b.png">
